{{- if .Values.ClusterSecretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "{{ .Values.ClusterSecretStore.vault.server }}"
      path: "{{ .Values.ClusterSecretStore.vault.path }}"
      version: "{{ .Values.ClusterSecretStore.vault.version }}"
      auth:
        tokenSecretRef:
          name: "{{ .Values.ClusterSecretStore.vault.auth.secretname }}"
          key: "{{ .Values.ClusterSecretStore.vault.auth.key }}"
          namespace: "{{ .Values.ClusterSecretStore.vault.auth.namespace }}"
{{- end }}