apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: capten-cass
spec:
  cassandra:
    serverVersion: "4.0.1"
    serverImage: {{ .Values.image.serverImage }}
    telemetry:
      prometheus:
        enabled: true
    storageConfig:
      cassandraDataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512M
    networking: 
      hostNetwork: {{ .Values.networking.hostNetwork }}
    datacenters:
      - metadata:
          name: capten-cass
        size: {{ .Values.datacenters.size }}
    mgmtAPIHeap: 256Mi 
  stargate:
    size: 1
    heapSize: 256M
    telemetry:
      prometheus:
        enabled: true
  reaper:
    keyspace: reaper_db
