apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
data:
  PORT: {{ .Values.service.internalPort | default "8080" | quote }}