{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v0.22.1"
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: "v0.22.1"
    app: tekton-triggers-controller
    version: "v0.22.1"
  name: tekton-triggers-controller-monitor
spec:
  endpoints:
  - port: http-metrics
    metricRelabelings:
      - action: replace
        regex: .*
        replacement: {{ .Values.clustername }}
        separator: ;
        targetLabel: cluster_name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-triggers
{{- end }}
