server:
  enabled: true
  sidecarContainers:
  image:
    repository: ghcr.io/kube-tarian/helmrepo-supporting-tools/server
    tag: 1.17.5
    pullPolicy: IfNotPresent
  
  config:
    persistence:
      default:
        driver: "cassandra"
        cassandra:
          hosts: ["capten-cass-capten-cass-service"]
          user: "capten-cass-superuser"
          existingSecret: "capten-cass-superuser"

        sql:
          user: "capten-cass-superuser"
          password: "capten-cass-superuser"

      visibility:
        driver: "cassandra"
        cassandra:
          hosts: ["capten-cass-capten-cass-service"]
          user: "capten-cass-superuser"
          existingSecret: "capten-cass-superuser"

        sql:
          user: "capten-cass-superuser"
          password: "capten-cass-superuser"
    
    autoscaling:
      enabled: false

frontend:
  autoscaling:
  enabled: false
history:
  autoscaling:
  enabled: false
matching:
  autoscaling:
  enabled: false
worker:
  autoscaling:
  enabled: false  

admintools:
  enabled: true
  image:
    repository: ghcr.io/kube-tarian/helmrepo-supporting-tools/admin-tools
    tag: 1.17.5
    pullPolicy: IfNotPresent

web:
  enabled: true
  image:
    repository: ghcr.io/kube-tarian/helmrepo-supporting-tools/ui
    tag: latest
    pullPolicy: IfNotPresent


cassandra:
  image:
    repo: ghcr.io/kube-tarian/helmrepo-supporting-tools/cassandra
    tag: 3.11.3
    pullPolicy: IfNotPresent

