apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: secret-new
  data:
  - secretKey: nats-token
    remoteRef:
      key: secret/generic/nats/auth-token
      property: nats
