apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: vault-aws-secret
  data:
  - secretKey: access_key
    remoteRef:
      key: provider-creds/aws-default
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: provider-creds/aws-default
      property: secret_key 
