apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ml-server.name" . }}-configmap
  labels:
    {{- include "ml-server.labels" . | nindent 4 }}
data:
  LOGGING_LEVEL: "{{ .Values.env.loggingLevel }}"
  HOST: "0.0.0.0"
  PORT: "{{ .Values.service.port }}"
  ML_SERVER_ADDRESS_DNS: "{{ .Values.env.serverAddress }}:{{ .Values.service.port }}"
  DB_ADDRESSES: "{{.Values.env.migrate_db_cassandra.db_address}}"
  DB_SERVICE_USERNAME: "{{.Values.env.migrate_db_cassandra.service_db_username}}"
  DB_NAME: "{{ .Values.env.migrate_db_cassandra.db_name }}"
  DB_SERVICE_PASSWD: "{{ .Values.env.migrate_db_cassandra.service_db_password }}"
  ML_DATA_COLLECTOR_IMAGE: "{{ .Values.env.ml_data_collector.image }}"
  ML_MODEL_IMAGE: "{{ .Values.env.ml_model.image }}"
  ML_MODEL_TRAIN_IMAGE: "{{ .Values.env.ml_model.train_image }}"
  IS_AGENT_INTEGRATE: "{{ .Values.env.ml_agent.is_integrated }}"
  IS_MLMODEL_INTEGRATE: "{{ .Values.env.ml_model.is_integrated }}"
  DOCKER_SECRET_NAMESPACE: "{{ .Values.env.docker.namespace }}"
  DOCKER_SECRET_NAME: "{{ .Values.env.docker.secret_name }}"
  DC_DOMAIN_NAME: "{{ .Values.env.ml_data_collector.domian }}"
  ASTRA_DB_ID: {{ .Values.asterDB.dbId | quote }}
  ASTRA_DB_REGION: {{ .Values.asterDB.region | quote }}
  ASTRA_DB_KEYSPACE: {{ .Values.asterDB.keyspace | quote }}
  APPLICATION_NAME: {{ .Values.opentelemetry.appName | quote }}
  OPTE_URL: {{ .Values.opentelemetry.url | quote }}
  IS_OPTE_INSECURE: {{ .Values.opentelemetry.insecure | quote }}
  IS_OPTEL_ENABLED: {{ .Values.opentelemetry.isEnabled | quote }}
  RETRY_LIMIT: {{ .Values.env.retryLimit | quote }}
  SLEEP_INTERVAL: {{ .Values.env.sleepInterval | quote }}
  ISTIO_GATEWAY_FOR_DC: {{ .Values.istio.istio_gateway }}
  IAM_URL: {{.Values.iam.address}}
  ORY_ENTITY_NAME: {{ .Values.ory.entityName }}
  ORY_CRED_IDENTIFIER: {{ .Values.ory.credIdentifier }}
  CERBOS_URL: {{ .Values.cerbos.url }}
  CERBOS_USERNAME: {{ .Values.cerbos.userName }}
  CERBOS_ENTITY_NAME: {{ .Values.cerbos.entityName }}
  VAULT_ADDR: {{ .Values.vault.address }}
  VAULT_ROLE: {{ .Values.vault.role }}
  VAULT_AUTH_MOUNT: {{ .Values.vault.authMount }}
  ASTRA_CRED_IDENTIFIER: {{ .Values.asterDB.credidentifier | quote }}
  ASTRA_ENTITY_NAME: {{ .Values.asterDB.entityname | quote }}
  AUTH_ENABLED: {{ .Values.env.auth.enabled | quote }}
  SERVICE_REGISTER: {{ .Values.env.auth.enabled| quote }}
