{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "ml-server.fullname" . }}-vs
  labels:
    {{- include "ml-server.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.istio.istio_gateway }}
  hosts:
    - {{ .Values.istio.host }}
  http:
    - corsPolicy:
        allowCredentials: true
        allowHeaders:
          - '*'
        allowMethods:
          - GET
          - OPTIONS
          - PUT
          - DELETE
          - POST
        allowOrigins:
          - regex: .*
      route:
        - destination:
            host: {{ include "ml-server.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      timeout: 30s
{{- end }}
