apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-server.name" . }}
  labels:
    {{- include "ml-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: grpc-http
  selector:
    {{- include "ml-server.selectorLabels" . | nindent 4 }}
