apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-role-mlserver
data:
  roleName: vault-role-mlserver
  policyNames: {{ .Values.vault.policyNames | quote }}
  servieAccounts: {{ include "ml-server.serviceAccountName" . }}
  servieAccountNameSpaces: {{ .Release.Namespace }}
