apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-label-mutation
spec:
  rules:
  - name: add-label
    match:
      any:   
      - resources:
          kinds:
            - ServiceMonitor
    mutate:
      patchesJson6902: |-
        - op: add
          path: /metadata/labels/release
          value: prometheus
  - name: add-annotation
    match:
      any:
      - resources:
          kinds:
            - ServiceMonitor
          names:
            - kubescape-monitor
    mutate:
      patchesJson6902: |-
        - op: add
          path: /metadata/annotations/prometheus.io~1scrape
          value: "true"