apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-json-api
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: JSON-API
        type: marcusolsson-json-datasource
        access: proxy
        url: {{ .Values.datasources.jsonApi.url }}