{{- if .Values.slack.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "monitoring.fullname" . }}-slack-webhook
  namespace: {{ .Release.Namespace }}
data:
  webhookURL: {{ .Values.slack.webhook | b64enc }}
{{- end }}
